workflows:
  android-release:
    name: Android Release Workflow
    max_build_duration: 120
    environment:
      flutter: 3.13.10
      xcode: latest
      cocoapods: default
      vars:
        ANDROID_KEYSTORE_BASE64: EncryptedKeystoreHere
        ANDROID_KEYSTORE_PASSWORD: EncryptedPasswordHere
        ANDROID_KEY_ALIAS: keyAliasHere
        ANDROID_KEY_PASSWORD: keyPasswordHere
      gradle_cache: true
      cache:
        - .pub-cache
        - build
    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get
      - name: Clean previous builds
        script: |
          flutter clean
      - name: Build Android AppBundle
        script: |
          flutter build appbundle --release --no-shrink
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - your_qubey.ai@gmail.com
        on_success: all
        on_failure: all


