workflows:
  android-release-firebase:
    name: Android Release with Firebase
    max_build_duration: 120

    environment:
      flutter: 3.24.3
      xcode: latest
      java: 17
      vars:
        ANDROID_KEYSTORE_BASE64: EncryptedKeystoreHere
        ANDROID_KEYSTORE_PASSWORD: KeystorePasswordHere
        ANDROID_KEY_ALIAS: KeyAliasHere
        ANDROID_KEY_PASSWORD: KeyPasswordHere

    scripts:

      - name: Force update Gradle wrapper to 8.11.1
        script: |
          echo "Updating Gradle wrapper..."
          mkdir -p android/gradle/wrapper
          echo "distributionBase=GRADLE_USER_HOME" > android/gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> android/gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> android/gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> android/gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-8.11.1-all.zip" >> android/gradle/wrapper/gradle-wrapper.properties
          cat android/gradle/wrapper/gradle-wrapper.properties

      - name: Set key.properties for signing
        script: |
          echo "storePassword=$ANDROID_KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$ANDROID_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$ANDROID_KEY_ALIAS" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Clean previous builds and Gradle cache
        script: |
          flutter clean
          echo "Cleaning Gradle cache again..."
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper

      - name: Build AppBundle
        script: |
          # Ensure proper signing and Java 8 desugaring
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties
          echo "org.gradle.jvmargs=-Dfile.encoding=UTF-8 --add-opens java.base/java.lang=ALL-UNNAMED" >> android/gradle.properties

          # Build AppBundle with explicit build-name and build-number
          flutter build appbundle --release --no-tree-shake-icons --build-name=1.0.0 --build-number=1 --verbose

          # Ensure the AAB exists at the expected path
          mkdir -p build/app/outputs/bundle/release
          cp build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/app-release.aab || echo "AAB not found, check logs above"

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab

