workflows:
  android-release-firebase:
    name: Android Release with Firebase
    max_build_duration: 120

    environment:
      flutter: 3.24.3
      xcode: latest
      java: 17
      vars:
        ANDROID_KEYSTORE_BASE64: EncryptedKeystoreHere
        ANDROID_KEYSTORE_PASSWORD: KeystorePasswordHere
        ANDROID_KEY_ALIAS: KeyAliasHere
        ANDROID_KEY_PASSWORD: KeyPasswordHere

    scripts:
     
      - name: Set key.properties for signing
        script: |
          echo "storePassword=$ANDROID_KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$ANDROID_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$ANDROID_KEY_ALIAS" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

    
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Clean previous builds and Gradle cache
        script: |
          flutter clean
          echo "Cleaning Gradle cache again..."
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper

      - name: Build Android AppBundle
        script: |
          flutter build appbundle --release

    artifacts:
      - build/**/outputs/**/*.aab

