workflows:
  android-release-firebase:
    name: Android Release with Firebase
    max_build_duration: 120

    environment:
      flutter: 3.24.3
      xcode: latest
      java: 17
      vars:
        ANDROID_KEYSTORE_BASE64: EncryptedKeystoreHere
        ANDROID_KEYSTORE_PASSWORD: KeystorePasswordHere
        ANDROID_KEY_ALIAS: KeyAliasHere
        ANDROID_KEY_PASSWORD: KeyPasswordHere

    scripts:

      # 🔥 1. Delete old Gradle wrapper & cache (IMPORTANT)
      - name: Delete old Gradle wrapper from cache
        script: |
          echo "Deleting old Gradle wrapper & cache..."
          rm -rf ~/.gradle/wrapper
          rm -rf ~/.gradle/caches

      # 🔥 2. Force-update Gradle wrapper to 8.11.1 (REQUIRED)
      - name: Update Gradle wrapper in project
        script: |
          echo "Updating Gradle wrapper to 8.11.1"
          sed -i.bak 's#distributionUrl=.*#distributionUrl=https\://services.gradle.org/distributions/gradle-8.11.1-all.zip#g' android/gradle/wrapper/gradle-wrapper.properties
          cat android/gradle/wrapper/gradle-wrapper.properties

      # 🔥 3. Validate wrapper (stops build if wrong)
      - name: Validate Gradle version
        script: |
          echo "Validating gradle version..."
          grep "8.11.1" android/gradle/wrapper/gradle-wrapper.properties || (echo "Gradle version incorrect!" && exit 1)

      - name: Set key.properties for signing
        script: |
          echo "storePassword=$ANDROID_KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$ANDROID_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$ANDROID_KEY_ALIAS" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Clean previous builds and Gradle cache
        script: |
          flutter clean
          echo "Cleaning Gradle cache again..."
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper

      - name: Build Android AppBundle
        script: |
          flutter build appbundle --release

    artifacts:
      - build/**/outputs/**/*.aab
