// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'app00';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String QUBEY_FORGOTPASSWORD_SCREEN = 'assets/images/qubey forgotpassword screen.jpg';
  static const String QUBEY_LOGO = 'assets/logo/qubey logo.jpg';
  static const String UNTITLED_DESIGN = 'assets/welcome screen/Untitled design.png';
}
